monolog:
  handlers:
    main:
      type: fingers_crossed
      level: error
      action_level: error
      handler: nested
      excluded_http_codes: [404, 405]
      buffer_size: 32
    business_event_handler_buffer:
      level: error
    nested:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: error
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]